# Generated by Django 4.0.7 on 2022-11-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_customer_alter_order_transcation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transcation_id',
            field=models.CharField(default='C70C4', editable=False, max_length=50),
        ),
    ]
